In [1]:
import pandas as pd

In [2]:
results = pd.read_csv("./results.csv")

In [3]:
results

Unnamed: 0  acc      loss  norm/attention_head.w_q.weight  \
0            0  0.0  1.290940                        0.005675   
1            1  0.0  1.260921                        0.004757   
2            2  0.0  1.232092                        0.003881   
3            3  0.0  1.204448                        0.003047   
4            4  0.0  1.177976                        0.002254   
..         ...  ...       ...                             ...   
95          95  1.0  0.516938                        0.003784   
96          96  1.0  0.512520                        0.003803   
97          97  1.0  0.508071                        0.003804   
98          98  1.0  0.503592                        0.003795   
99          99  1.0  0.499087                        0.003789   

    norm/attention_head.w_q.bias  norm/attention_head.w_k.weight  \
0                       0.005675                        0.015899   
1                       0.004757                        0.014675   
2                       0.003881                        0.013516   
3                       0.003047                        0.012424   
4                       0.002254                        0.011402   
..                           ...                             ...   
95                      0.003784                        0.002583   
96                      0.003803                        0.002961   
97                      0.003804                        0.003375   
98                      0.003795                        0.003644   
99                      0.003789                        0.003649   

    norm/attention_head.w_k.bias  norm/attention_head.w_v.weight  \
0                   6.317945e-10                        0.241893   
1                   3.055902e-10                        0.229834   
2                   1.771811e-10                        0.218386   
3                   4.692852e-10                        0.207558   
4                   2.968020e-10                        0.197356   
..                           ...                             ...   
95                  1.545696e-08                        0.086415   
96                  4.393040e-09                        0.086775   
97                  1.478165e-08                        0.087071   
98                  7.708945e-09                        0.087281   
99                  4.861647e-09                        0.087401   

    norm/attention_head.w_v.bias  norm/attention_head.w_o.weight  \
0                       0.346992                        0.169203   
1                       0.327761                        0.159038   
2                       0.309436                        0.150341   
3                       0.292035                        0.143089   
4                       0.275572                        0.137224   
..                           ...                             ...   
95                      0.013024                        0.093344   
96                      0.014315                        0.094205   
97                      0.015104                        0.094720   
98                      0.015191                        0.094826   
99                      0.014503                        0.094501   

    norm/attention_head.w_o.bias  norm/unembedding.bias  eval_acc  
0                       0.565075               0.565075  0.000000  
1                       0.546886               0.546886  0.000000  
2                       0.528917               0.528917  0.000000  
3                       0.511211               0.511211  0.000000  
4                       0.493804               0.493804  0.017778  
..                           ...                    ...       ...  
95                      0.055982               0.055982  1.000000  
96                      0.055119               0.055119  1.000000  
97                      0.054491               0.054491  1.000000  
98                      0.054135               0.054135  1.000000  
99                      

In [4]:
import plotly.express as px

In [5]:
px.line(results, y=["loss", "acc", "eval_acc"])

In [6]:
import torch
state_dict = torch.load("./model.pth")

/var/folders/zb/9vg2j2017xvf9h4y5dqdrj4r0000gn/T/ipykernel_42908/1863357981.py:2: FutureWarning:

You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.



In [7]:
{name: param.shape for name, param in state_dict.items()}

{'embedding.weight': torch.Size([3, 3]),
 'attention_head.w_q.weight': torch.Size([2, 3]),
 'attention_head.w_q.bias': torch.Size([2]),
 'attention_head.w_k.weight': torch.Size([2, 3]),
 'attention_head.w_k.bias': torch.Size([2]),
 'attention_head.w_v.weight': torch.Size([2, 3]),
 'attention_head.w_v.bias': torch.Size([2]),
 'attention_head.w_o.weight': torch.Size([3, 2]),
 'attention_head.w_o.bias': torch.Size([3]),
 'mlp.0.weight': torch.Size([3, 3]),
 'mlp.0.bias': torch.Size([3]),
 'mlp.2.weight': torch.Size([3, 3]),
 'mlp.2.bias': torch.Size([3]),
 'unembedding.weight': torch.Size([3, 3]),
 'unembedding.bias': torch.Size([3])}

In [8]:
dataset = torch.load("./dataset.pt")

/var/folders/zb/9vg2j2017xvf9h4y5dqdrj4r0000gn/T/ipykernel_42908/1705551896.py:1: FutureWarning:

You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.



In [9]:
list(map(lambda ls: torch.stack(ls),(zip(*dataset["eval"]))))[1]

tensor([0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
        0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0,
        1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
        1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
        1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0,
        1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
        0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1,
        0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
        1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
        1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
        1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,

In [10]:
from train_transformer import eval_epoch
from torch.utils.data import DataLoader

In [11]:
from miexp.models.interptransformer import SingleHeadTransformer, SingleHeadTransformerNoEmbedding


model = SingleHeadTransformerNoEmbedding(vocab_size=2, head_dim=2)
model.load_state_dict(state_dict)

<All keys matched successfully>

In [12]:
type(model)

miexp.models.interptransformer.SingleHeadTransformerNoEmbedding

In [13]:
eval_dl = DataLoader(dataset["eval"], batch_size=32, shuffle=False)
res = eval_epoch(model, eval_dl, device="mps")

In [14]:
eval_results = eval_epoch(model, eval_dl, torch.device("mps"))
eval_acc = torch.argmax(
    torch.tensor(eval_results["probabilities"]), dim=1
) == torch.tensor(eval_results["correct_outputs"])
eval_acc.float().mean().item()

1.0

In [15]:
torch.set_printoptions(sci_mode=False)

In [16]:
probs = {name: torch.tensor(val) for name, val in res.items()}["probabilities"]

In [17]:
corr = {name: torch.tensor(val) for name, val in res.items()}["correct_outputs"]

In [18]:
(torch.argmax(
            probs, dim=1
        ) == corr).float().mean()

tensor(1.)

In [19]:
{name: torch.tensor(val) for name, val in res.items()}["probabilities"].argmax(dim=1).float().sum()

tensor(367.)

In [20]:
{name: torch.tensor(val) for name, val in res.items()}["correct_outputs"].bincount()

tensor([533, 367])

In [44]:
from plotly.subplots import make_subplots

# Filter out biases from state_dict
filtered_state_dict = state_dict # {k: v for k, v in state_dict.items() if 'bias' not in k}

import plotly.graph_objects as go

# Create a subplot grid
num_matrices = len(filtered_state_dict)
fig = make_subplots(rows=num_matrices // 3 + 1, cols=3, subplot_titles=list(state_dict.keys()))

fig.update_layout(
    height=300*num_matrices / 3,  # Adjust height based on the number of matrices
    coloraxis={'colorscale': 'Viridis'},
    showlegend=False,
    yaxis=dict(visible=True,autorange='reversed')
)

# Add a heatmap for each matrix in state_dict
for i, (name, matrix) in enumerate(filtered_state_dict.items()):
    fig.add_trace(
        go.Heatmap(z=matrix.cpu().numpy(), coloraxis="coloraxis"),
        row=(i // 3)+1, col=(i % 3) + 1
    )
    fig.update_layout(
        height=300*num_matrices / 3,  # Adjust height based on the number of matrices
        coloraxis={'colorscale': 'Viridis'},
        showlegend=False,
        yaxis=dict(visible=True,autorange='reversed')
    )

# Update layout
fig.update_layout(
    height=300*num_matrices / 3,  # Adjust height based on the number of matrices
    coloraxis={'colorscale': 'Viridis'},
    showlegend=False,
    yaxis=dict(visible=True,autorange='reversed')
)

fig.show()

In [24]:
main_query = state_dict["attention_head.w_q.weight"][:, 2]
main_query

tensor([-0.0404, -0.0190], device='mps:0')

In [27]:
keys = state_dict["attention_head.w_k.weight"].T
keys

tensor([[0.1805, 0.2652],
        [0.3405, 0.1047],
        [1.1778, 0.7704]], device='mps:0')

In [29]:
prods = torch.matmul(keys, main_query)
prods

tensor([-0.0123, -0.0158, -0.0623], device='mps:0')

In [37]:
values = state_dict["attention_head.w_v.weight"].T
values

tensor([[ 1.4987,  0.2994],
        [-1.0814, -0.8250],
        [-0.2797,  0.0595]], device='mps:0')

In [43]:
effective_values = prods.unsqueeze(1) * values

In [45]:
effective_values

tensor([[-0.0185, -0.0037],
        [ 0.0170,  0.0130],
        [ 0.0174, -0.0037]], device='mps:0')

In [69]:
dataset["eval"][0]  

(tensor([0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1]),
 tensor(0, dtype=torch.int32))

In [70]:
x, y = dataset["eval"][0]


In [71]:
x = torch.cat([torch.tensor([2]), x])

In [73]:
model(x.unsqueeze(0))

tensor([[ 2.3882,  1.6289, -0.1878]], grad_fn=<AddmmBackward0>)

In [74]:
model.to("cpu")

SingleHeadTransformerNoEmbedding(
  (embedding): Embedding(3, 3)
  (attention_head): AttentionHead(
    (w_q): Linear(in_features=3, out_features=2, bias=True)
    (w_k): Linear(in_features=3, out_features=2, bias=True)
    (w_v): Linear(in_features=3, out_features=2, bias=True)
    (w_o): Linear(in_features=2, out_features=3, bias=True)
  )
  (mlp): Sequential(
    (0): Linear(in_features=3, out_features=3, bias=True)
    (1): ReLU()
    (2): Linear(in_features=3, out_features=3, bias=True)
  )
  (unembedding): Linear(in_features=3, out_features=3, bias=True)
)

In [75]:
px.imshow(model.embedding(x).T.detach().cpu().numpy())


In [76]:
x = model.embedding(x)
q = model.attention_head.w_q(x)
k = model.attention_head.w_k(x)
v = model.attention_head.w_v(x)
A = torch.softmax(q @ k.transpose(-1, -2) / (model.attention_head.head_dim**0.5), dim=-1)  

In [77]:
px.imshow(A.detach().cpu().numpy())

In [78]:
px.imshow((A @ v).detach().cpu().numpy())

In [79]:
px.imshow(model.attention_head.w_o(A @ v).detach().cpu().numpy())