In [1]:
import pandas as pd

In [2]:
results = pd.read_csv("./results.csv")

In [3]:
results

Unnamed: 0    acc      loss  norm/attention_head.w_q.weight  \
0             0  0.565  1.016895                        0.000256   
1             1  0.565  0.998433                        0.000144   
2             2  0.565  0.980488                        0.000255   
3             3  0.565  0.963276                        0.000211   
4             4  0.565  0.946782                        0.000147   
..          ...    ...       ...                             ...   
295         295  1.000  0.082189                        0.003402   
296         296  1.000  0.081728                        0.001398   
297         297  1.000  0.081056                        0.000693   
298         298  1.000  0.080790                        0.004313   
299         299  1.000  0.080430                        0.006525   

     norm/attention_head.w_q.bias  norm/attention_head.w_k.weight  \
0                        0.000256                        0.000476   
1                        0.000144                        0.000152   
2                        0.000255                        0.000265   
3                        0.000211                        0.000269   
4                        0.000147                        0.000221   
..                            ...                             ...   
295                      0.003402                        0.177116   
296                      0.001398                        0.063518   
297                      0.000693                        0.051179   
298                      0.004313                        0.251909   
299                      0.006525                        0.395193   

     norm/attention_head.w_k.bias  norm/attention_head.w_v.weight  \
0                    8.876668e-10                        0.061993   
1                    5.002221e-10                        0.049204   
2                    3.565219e-10                        0.056513   
3                    2.492015e-10                        0.052492   
4                    1.055014e-10                        0.045214   
..                            ...                             ...   
295                  5.029142e-08                        0.037693   
296                  1.396984e-08                        0.022052   
297                  2.235174e-08                        0.021308   
298                  1.490116e-08                        0.050358   
299                  9.313226e-09                        0.070706   

     norm/attention_head.w_v.bias  norm/attention_head.w_o.weight  \
0                        0.068680                        0.208989   
1                        0.030395                        0.213288   
2                        0.052733                        0.202163   
3                        0.038269                        0.202767   
4                        0.023220                        0.206607   
..                            ...                             ...   
295                      0.046050                        0.019106   
296                      0.014364                        0.027606   
297                      0.014460                        0.022745   
298                      0.065013                        0.018824   
299                      0.097982                        0.031655   

     norm/attention_head.w_o.bias  eval_acc  
0                        0.320381  0.603333  
1                        0.316087  0.603333  
2                        0.292157  0.603333  
3                        0.285472  0.603333  
4                        0.284461  0.603333  
..                            ...       ...  
295                      0.015342  1.000000  
296                      0.008172  1.000000  
297                      0.010063  1.000000  
298                      0.019492  1.000000  
299                      0.018758  1.000000  

[300 rows x 12 columns]

In [4]:
import plotly.express as px

In [50]:
px.line(results, y=["loss", "acc", "eval_acc"])

In [6]:
import torch
state_dict = torch.load("./model.pth")

/var/folders/zb/9vg2j2017xvf9h4y5dqdrj4r0000gn/T/ipykernel_38777/1863357981.py:2: FutureWarning:

You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.



In [7]:
{name: param.shape for name, param in state_dict.items()}

{'embedding.weight': torch.Size([3, 3]),
 'attention_head.w_q.weight': torch.Size([1, 3]),
 'attention_head.w_q.bias': torch.Size([1]),
 'attention_head.w_k.weight': torch.Size([1, 3]),
 'attention_head.w_k.bias': torch.Size([1]),
 'attention_head.w_v.weight': torch.Size([1, 3]),
 'attention_head.w_v.bias': torch.Size([1]),
 'attention_head.w_o.weight': torch.Size([3, 1]),
 'attention_head.w_o.bias': torch.Size([3]),
 'mlp.0.weight': torch.Size([3, 3]),
 'mlp.0.bias': torch.Size([3]),
 'mlp.2.weight': torch.Size([3, 3]),
 'mlp.2.bias': torch.Size([3]),
 'unembedding.weight': torch.Size([3, 3])}

In [8]:
dataset = torch.load("./dataset.pt")

/var/folders/zb/9vg2j2017xvf9h4y5dqdrj4r0000gn/T/ipykernel_38777/1705551896.py:1: FutureWarning:

You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.



In [9]:
list(map(lambda ls: torch.stack(ls),(zip(*dataset["eval"]))))[1]

tensor([0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
        1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
        0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
        1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1,
        1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
        0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
        0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
        1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1,
        1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
        0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
        1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
        0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,

In [10]:
from train_transformer import eval_epoch
from torch.utils.data import DataLoader

In [11]:


model = SingleHeadTransformerNoEmbedding(vocab_size=2, head_dim=1)
model.load_state_dict(state_dict)

<All keys matched successfully>

In [12]:
type(model)

miexp.models.interptransformer.SingleHeadTransformerNoEmbedding

In [13]:
eval_dl = DataLoader(dataset["eval"], batch_size=32, shuffle=False)
res = eval_epoch(model, eval_dl, device="mps")

In [14]:
eval_results = eval_epoch(model, eval_dl, torch.device("mps"))
eval_acc = torch.argmax(
    torch.tensor(eval_results["probabilities"]), dim=1
) == torch.tensor(eval_results["correct_outputs"])
eval_acc.float().mean().item()

1.0

In [15]:
torch.set_printoptions(sci_mode=False)

In [16]:
probs = {name: torch.tensor(val) for name, val in res.items()}["probabilities"]

In [17]:
corr = {name: torch.tensor(val) for name, val in res.items()}["correct_outputs"]

In [18]:
(torch.argmax(
            probs, dim=1
        ) == corr).float().mean()

tensor(1.)

In [19]:
{name: torch.tensor(val) for name, val in res.items()}["probabilities"].argmax(dim=1).float().sum()

tensor(238.)

In [20]:
{name: torch.tensor(val) for name, val in res.items()}["correct_outputs"].bincount()

tensor([362, 238])

In [49]:
from plotly.subplots import make_subplots

# Filter out biases from state_dict
filtered_state_dict = state_dict # {k: v for k, v in state_dict.items() if 'bias' not in k}

import plotly.graph_objects as go

# Create a subplot grid
num_matrices = len(filtered_state_dict)
fig = make_subplots(rows=num_matrices // 3 + 1, cols=3, subplot_titles=list(state_dict.keys()))

fig.update_layout(
    height=300*num_matrices / 3,  # Adjust height based on the number of matrices
    coloraxis={'colorscale': 'Viridis'},
    showlegend=False,
)

# Add a heatmap for each matrix in state_dict
for i, (name, matrix) in enumerate(filtered_state_dict.items()):
    fig.add_trace(
        go.Heatmap(z=matrix.cpu().numpy(), coloraxis="coloraxis"),
        row=(i // 3)+1, col=(i % 3) + 1,
    )

fig.show()

In [22]:
state_dict["attention_head.w_q.weight"][0, 2] * state_dict["attention_head.w_k.weight"] * state_dict["attention_head.w_v.weight"]

tensor([[ 0.3412, -0.3071, -0.7136]], device='mps:0')

In [23]:
main_query = state_dict["attention_head.w_q.weight"][:, 2]
main_query

tensor([-0.3029], device='mps:0')

In [24]:
keys = state_dict["attention_head.w_k.weight"].T
keys

tensor([[-0.2547],
        [-0.2227],
        [ 3.4944]], device='mps:0')

In [25]:
prods = torch.matmul(keys, main_query)
prods

tensor([ 0.0771,  0.0675, -1.0584], device='mps:0')

In [26]:
values = state_dict["attention_head.w_v.weight"].T
values

tensor([[ 4.4229],
        [-4.5519],
        [ 0.6742]], device='mps:0')

In [27]:
effective_values = prods.unsqueeze(1) * values

In [28]:
effective_values

tensor([[ 0.3412],
        [-0.3071],
        [-0.7136]], device='mps:0')

In [29]:
dataset["eval"][0]  

(tensor([0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0]),
 tensor(0, dtype=torch.int32))

In [30]:
x, y = dataset["eval"][0]


In [31]:
model.to("cpu")

SingleHeadTransformerNoEmbedding(
  (embedding): Embedding(3, 3)
  (attention_head): AttentionHead(
    (w_q): Linear(in_features=3, out_features=1, bias=True)
    (w_k): Linear(in_features=3, out_features=1, bias=True)
    (w_v): Linear(in_features=3, out_features=1, bias=True)
    (w_o): Linear(in_features=1, out_features=3, bias=True)
  )
  (mlp): Sequential(
    (0): Linear(in_features=3, out_features=3, bias=True)
    (1): ReLU()
    (2): Linear(in_features=3, out_features=3, bias=True)
  )
  (unembedding): Linear(in_features=3, out_features=3, bias=False)
)

In [32]:
real_output = model(x.unsqueeze(0))

In [33]:
x = torch.cat([torch.tensor([2]), x])

In [34]:
px.imshow(model.embedding(x).T.detach().cpu().numpy())


In [35]:
x = model.embedding(x)
q = model.attention_head.w_q(x)
k = model.attention_head.w_k(x)
v = model.attention_head.w_v(x)
A = torch.softmax(q @ k.transpose(-1, -2) / (model.attention_head.head_dim**0.5), dim=-1)  

In [36]:
A.shape

torch.Size([21, 21])

In [37]:
print(q[0], k[0], v[0], A[0])

tensor([-1.2610], grad_fn=<SelectBackward0>) tensor([3.5933], grad_fn=<SelectBackward0>) tensor([1.3525], grad_fn=<SelectBackward0>) tensor([0.0004, 0.0507, 0.0507, 0.0507, 0.0487, 0.0487, 0.0507, 0.0507, 0.0487,
        0.0507, 0.0507, 0.0507, 0.0487, 0.0507, 0.0507, 0.0507, 0.0507, 0.0487,
        0.0487, 0.0487, 0.0507], grad_fn=<SelectBackward0>)


In [38]:
px.imshow(A.detach().cpu().numpy())

In [39]:
px.imshow((A @ v).detach().cpu().numpy())

In [40]:
px.imshow(model.attention_head.w_o(A @ v).detach().cpu().numpy())

In [41]:
A[0].unsqueeze(1) * v

tensor([[ 0.0006],
        [ 0.2585],
        [ 0.2585],
        [ 0.2585],
        [-0.1885],
        [-0.1885],
        [ 0.2585],
        [ 0.2585],
        [-0.1885],
        [ 0.2585],
        [ 0.2585],
        [ 0.2585],
        [-0.1885],
        [ 0.2585],
        [ 0.2585],
        [ 0.2585],
        [ 0.2585],
        [-0.1885],
        [-0.1885],
        [-0.1885],
        [ 0.2585]], grad_fn=<MulBackward0>)

In [42]:
atten_out = model.attention_head.w_o(A @ v)
atten_out

tensor([[ 9.1864, -1.3506, -4.9337],
        [ 8.9618, -1.2504, -4.8703],
        [ 8.9618, -1.2504, -4.8703],
        [ 8.9618, -1.2504, -4.8703],
        [ 9.2355, -1.3725, -4.9475],
        [ 9.2355, -1.3725, -4.9475],
        [ 8.9618, -1.2504, -4.8703],
        [ 8.9618, -1.2504, -4.8703],
        [ 9.2355, -1.3725, -4.9475],
        [ 8.9618, -1.2504, -4.8703],
        [ 8.9618, -1.2504, -4.8703],
        [ 8.9618, -1.2504, -4.8703],
        [ 9.2355, -1.3725, -4.9475],
        [ 8.9618, -1.2504, -4.8703],
        [ 8.9618, -1.2504, -4.8703],
        [ 8.9618, -1.2504, -4.8703],
        [ 8.9618, -1.2504, -4.8703],
        [ 9.2355, -1.3725, -4.9475],
        [ 9.2355, -1.3725, -4.9475],
        [ 9.2355, -1.3725, -4.9475],
        [ 8.9618, -1.2504, -4.8703]], grad_fn=<AddmmBackward0>)

In [43]:
real_atten_out = model.attention_head(x)
real_atten_out

tensor([[ 9.1864, -1.3506, -4.9337],
        [ 8.9618, -1.2504, -4.8703],
        [ 8.9618, -1.2504, -4.8703],
        [ 8.9618, -1.2504, -4.8703],
        [ 9.2355, -1.3725, -4.9475],
        [ 9.2355, -1.3725, -4.9475],
        [ 8.9618, -1.2504, -4.8703],
        [ 8.9618, -1.2504, -4.8703],
        [ 9.2355, -1.3725, -4.9475],
        [ 8.9618, -1.2504, -4.8703],
        [ 8.9618, -1.2504, -4.8703],
        [ 8.9618, -1.2504, -4.8703],
        [ 9.2355, -1.3725, -4.9475],
        [ 8.9618, -1.2504, -4.8703],
        [ 8.9618, -1.2504, -4.8703],
        [ 8.9618, -1.2504, -4.8703],
        [ 8.9618, -1.2504, -4.8703],
        [ 9.2355, -1.3725, -4.9475],
        [ 9.2355, -1.3725, -4.9475],
        [ 9.2355, -1.3725, -4.9475],
        [ 8.9618, -1.2504, -4.8703]], grad_fn=<AddmmBackward0>)

In [44]:
real_output

tensor([[ 9.1864, -1.3506, -3.9337]], grad_fn=<MmBackward0>)

In [45]:
real_atten_out + x

tensor([[ 9.1864, -1.3506, -3.9337],
        [ 9.9618, -1.2504, -4.8703],
        [ 9.9618, -1.2504, -4.8703],
        [ 9.9618, -1.2504, -4.8703],
        [ 9.2355, -0.3725, -4.9475],
        [ 9.2355, -0.3725, -4.9475],
        [ 9.9618, -1.2504, -4.8703],
        [ 9.9618, -1.2504, -4.8703],
        [ 9.2355, -0.3725, -4.9475],
        [ 9.9618, -1.2504, -4.8703],
        [ 9.9618, -1.2504, -4.8703],
        [ 9.9618, -1.2504, -4.8703],
        [ 9.2355, -0.3725, -4.9475],
        [ 9.9618, -1.2504, -4.8703],
        [ 9.9618, -1.2504, -4.8703],
        [ 9.9618, -1.2504, -4.8703],
        [ 9.9618, -1.2504, -4.8703],
        [ 9.2355, -0.3725, -4.9475],
        [ 9.2355, -0.3725, -4.9475],
        [ 9.2355, -0.3725, -4.9475],
        [ 9.9618, -1.2504, -4.8703]], grad_fn=<AddBackward0>)

In [46]:
model.unembedding.bias