In [136]:
import pandas as pd

In [137]:
results = pd.read_csv("./results.csv")

In [138]:
results

Unnamed: 0  acc      loss  norm/embedding.weight  \
0            0  0.4  1.015695               0.031013   
1            1  0.4  0.974480               0.022798   
2            2  0.4  0.942963               0.012400   
3            3  1.0  0.917906               0.013341   
4            4  0.6  0.894869               0.010379   
..         ...  ...       ...                    ...   
95          95  1.0  0.000015               0.000315   
96          96  1.0  0.000015               0.000308   
97          97  1.0  0.000014               0.000301   
98          98  1.0  0.000014               0.000295   
99          99  1.0  0.000014               0.000289   

    norm/attention_head.w_q.weight  norm/attention_head.w_q.bias  \
0                         0.004223                      0.001998   
1                         0.004846                      0.002296   
2                         0.003232                      0.001531   
3                         0.004306                      0.002037   
4                         0.001682                      0.000794   
..                             ...                           ...   
95                        0.000409                      0.000159   
96                        0.000399                      0.000155   
97                        0.000390                      0.000151   
98                        0.000382                      0.000148   
99                        0.000374                      0.000145   

    norm/attention_head.w_k.weight  norm/attention_head.w_k.bias  \
0                         0.004946                  1.495732e-09   
1                         0.005689                  2.718648e-10   
2                         0.003808                  2.261111e-10   
3                         0.005109                  4.606411e-10   
4                         0.002013                  7.037868e-11   
..                             ...                           ...   
95                        0.000545                  4.654917e-12   
96                        0.000532                  1.258774e-11   
97                        0.000520                  1.948797e-11   
98                        0.000509                  7.736816e-12   
99                        0.000499                  2.452225e-11   

    norm/attention_head.w_v.weight  norm/attention_head.w_v.bias  \
0                         0.085939                      0.050310   
1                         0.071077                      0.040005   
2                         0.040668                      0.020752   
3                         0.043386                      0.023030   
4                         0.035433                      0.015474   
..                             ...                           ...   
95                        0.000180                      0.000126   
96                        0.000175                      0.000123   
97                        0.000172                      0.000120   
98                        0.000168                      0.000118   
99                        0.000165                      0.000115   

    norm/attention_head.w_o.weight  norm/attention_head.w_o.bias  \
0                         0.093853                      0.093216   
1                         0.076968                      0.077047   
2                         0.055090                      0.051273   
3                         0.053197                      0.046042   
4                         0.054856                      0.037713   
..                             ...                           ...   
95                        0.000063                      0.000050   
96                        0.000061                      0.000049   
97                        0.000060                      0.000048   
98                        0.000059                      0.000047   
99                        0.000058                      0.000046   

    norm/mlp.0.weight  norm/mlp.0.bias  norm/mlp.2.weight  norm

In [139]:
import plotly.express as px

In [140]:
px.line(results, y=["loss", "acc", "eval_acc"])

In [148]:
import torch
state_dict = torch.load("./model.pth")

/var/folders/zb/9vg2j2017xvf9h4y5dqdrj4r0000gn/T/ipykernel_3009/1863357981.py:2: FutureWarning:

You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.



In [149]:
{name: param.shape for name, param in state_dict.items()}

{'embedding.weight': torch.Size([3, 8]),
 'attention_head.w_q.weight': torch.Size([8, 8]),
 'attention_head.w_q.bias': torch.Size([8]),
 'attention_head.w_k.weight': torch.Size([8, 8]),
 'attention_head.w_k.bias': torch.Size([8]),
 'attention_head.w_v.weight': torch.Size([8, 8]),
 'attention_head.w_v.bias': torch.Size([8]),
 'attention_head.w_o.weight': torch.Size([8, 8]),
 'attention_head.w_o.bias': torch.Size([8]),
 'mlp.0.weight': torch.Size([8, 8]),
 'mlp.0.bias': torch.Size([8]),
 'mlp.2.weight': torch.Size([8, 8]),
 'mlp.2.bias': torch.Size([8]),
 'unembedding.weight': torch.Size([3, 8]),
 'unembedding.bias': torch.Size([3])}

In [143]:
dataset = torch.load("./dataset.pt")

/var/folders/zb/9vg2j2017xvf9h4y5dqdrj4r0000gn/T/ipykernel_3009/1705551896.py:1: FutureWarning:

You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.



In [144]:
list(map(lambda ls: torch.stack(ls),(zip(*dataset["eval"]))))[1]

tensor([1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1,
        0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1,
        0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
        0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
        1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
        0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
        0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
        0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
        0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
        1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,

In [146]:
from train_transformer import eval_epoch
from torch.utils.data import DataLoader

In [155]:
from miexp.models.interptransformer import SingleHeadTransformer


model = SingleHeadTransformer(vocab_size=2, head_dim=8, hidden_dim=8)
model.load_state_dict(state_dict)

<All keys matched successfully>

In [156]:
type(model)

miexp.models.interptransformer.SingleHeadTransformer

In [157]:
eval_dl = DataLoader(dataset["eval"], batch_size=32, shuffle=False)
res = eval_epoch(model, eval_dl, device="mps")

In [161]:
torch.set_printoptions(sci_mode=False)

In [173]:
{name: torch.tensor(val) for name, val in res.items()}["probabilities"].sum(dim=0)

tensor([  634.4830,   360.4318,     0.0853])

In [171]:
{name: torch.tensor(val) for name, val in res.items()}["correct_outputs"].bincount()

tensor([586, 409])